server:
  port: 8088
spring:
  config:
    name: configServer
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          skipSslValidation: true
          timeout: 10
          default-label: main

